"""Tests for autogenerated endpoints."""


from app.autogenEndpoints import (
    crud_route_athlete,
    crud_route_athleteheat,
    crud_route_availablebonuses,
    crud_route_availablemoves,
    crud_route_competition,
    crud_route_event,
    crud_route_heat,
    crud_route_phase,
    crud_route_run_status,
    crud_route_scoredmoves,
    crud_route_scoresheet,
)


# Test routes to ensure they are properly set up
def test_competition_route_exists():
    """Test that the competition route exists and has correct configuration."""
    assert crud_route_competition.prefix == "/competition"
    assert "competition" in crud_route_competition.tags
    assert crud_route_competition.routes  # Ensure routes are defined


def test_event_route_exists():
    """Test that the event route exists and has correct configuration."""
    assert crud_route_event.prefix == "/event"
    assert "event" in crud_route_event.tags
    assert crud_route_event.routes  # Ensure routes are defined


def test_phase_route_exists():
    """Test that the phase route exists and has correct configuration."""
    assert crud_route_phase.prefix == "/phase"
    assert "phase" in crud_route_phase.tags
    assert crud_route_phase.routes  # Ensure routes are defined


def test_heat_route_exists():
    """Test that the heat route exists and has correct configuration."""
    assert crud_route_heat.prefix == "/heat"
    assert "heat" in crud_route_heat.tags
    assert crud_route_heat.routes  # Ensure routes are defined


def test_athlete_route_exists():
    """Test that the athlete route exists and has correct configuration."""
    assert crud_route_athlete.prefix == "/athlete"
    assert "athlete" in crud_route_athlete.tags
    assert crud_route_athlete.routes  # Ensure routes are defined


def test_athleteheat_route_exists():
    """Test that the athleteheat route exists and has correct configuration."""
    assert crud_route_athleteheat.prefix == "/athleteheat"
    assert "athleteheat" in crud_route_athleteheat.tags
    assert crud_route_athleteheat.routes  # Ensure routes are defined


def test_run_status_route_exists():
    """Test that the run_status route exists and has correct configuration."""
    assert crud_route_run_status.prefix == "/run_status"
    assert "run_status" in crud_route_run_status.tags
    assert crud_route_run_status.routes  # Ensure routes are defined


def test_scoredmoves_route_exists():
    """Test that the scoredmoves route exists and has correct configuration."""
    assert crud_route_scoredmoves.prefix == "/scoredmoves"
    assert "scoredmoves" in crud_route_scoredmoves.tags
    assert crud_route_scoredmoves.routes  # Ensure routes are defined


def test_availablemoves_route_exists():
    """Test that the availablemoves route exists and has correct configuration."""
    assert crud_route_availablemoves.prefix == "/availablemoves"
    assert "availablemoves" in crud_route_availablemoves.tags
    assert crud_route_availablemoves.routes  # Ensure routes are defined


def test_availablebonuses_route_exists():
    """Test that the availablebonuses route exists and has correct configuration."""
    assert crud_route_availablebonuses.prefix == "/availablebonuses"
    assert "availablebonuses" in crud_route_availablebonuses.tags
    assert crud_route_availablebonuses.routes  # Ensure routes are defined


def test_scoresheet_route_exists():
    """Test that the scoresheet route exists and has correct configuration."""
    assert crud_route_scoresheet.prefix == "/scoresheet"
    assert "scoresheet" in crud_route_scoresheet.tags
    assert crud_route_scoresheet.routes  # Ensure routes are defined
