"""Basic HTTP test for autogenerated endpoints."""

from app.autogenEndpoints import crud_route_competition
from main import app

# Create client but don't import TestClient to avoid issues
client = app.test_client if hasattr(app, 'test_client') else None


def test_basic_route_exists():
    """Test that the route is properly configured."""
    assert crud_route_competition.prefix == "/competition"
    assert "competition" in crud_route_competition.tags

    # Check that routes exist and at least include GET method
    assert crud_route_competition.routes

    # Find GET method
    get_route = None
    for route in crud_route_competition.routes:
        if route.methods and "GET" in route.methods:
            get_route = route
            break

    assert get_route is not None, "GET method not found in competition routes"
