"""Basic route existence tests for autogenerated HTTP endpoints."""
from app.autogenEndpoints import (
    crud_route_athlete,
    crud_route_athleteheat,
    crud_route_availablebonuses,
    crud_route_availablemoves,
    crud_route_competition,
    crud_route_event,
    crud_route_heat,
    crud_route_phase,
    crud_route_run_status,
    crud_route_scoredmoves,
    crud_route_scoresheet,
)


# Test route prefixes
def test_endpoints_have_correct_prefixes():
    """Test that all endpoints have the correct prefix."""
    assert crud_route_competition.prefix == "/competition"
    assert crud_route_event.prefix == "/event"
    assert crud_route_phase.prefix == "/phase"
    assert crud_route_heat.prefix == "/heat"
    assert crud_route_athlete.prefix == "/athlete"
    assert crud_route_athleteheat.prefix == "/athleteheat"
    assert crud_route_run_status.prefix == "/run_status"
    assert crud_route_scoredmoves.prefix == "/scoredmoves"
    assert crud_route_availablemoves.prefix == "/availablemoves"
    assert crud_route_availablebonuses.prefix == "/availablebonuses"
    assert crud_route_scoresheet.prefix == "/scoresheet"

# Test route tags


def test_endpoints_have_correct_tags():
    """Test that all endpoints have the correct tags."""
    assert "competition" in crud_route_competition.tags
    assert "event" in crud_route_event.tags
    assert "phase" in crud_route_phase.tags
    assert "heat" in crud_route_heat.tags
    assert "athlete" in crud_route_athlete.tags
    assert "athleteheat" in crud_route_athleteheat.tags
    assert "run_status" in crud_route_run_status.tags
    assert "scoredmoves" in crud_route_scoredmoves.tags
    assert "availablemoves" in crud_route_availablemoves.tags
    assert "availablebonuses" in crud_route_availablebonuses.tags
    assert "scoresheet" in crud_route_scoresheet.tags

# Test that routes exist


def test_endpoints_have_routes():
    """Test that all endpoints have routes defined."""
    assert crud_route_competition.routes
    assert crud_route_event.routes
    assert crud_route_phase.routes
    assert crud_route_heat.routes
    assert crud_route_athlete.routes
    assert crud_route_athleteheat.routes
    assert crud_route_run_status.routes
    assert crud_route_scoredmoves.routes
    assert crud_route_availablemoves.routes
    assert crud_route_availablebonuses.routes
    assert crud_route_scoresheet.routes
