#  Template npm-publish

#  This template allows you to publish your npm package, as defined in package.json, to npmjs.com or any other npm-like registry.
#  The workflow allows running tests, code linting and security scans on feature branches (as well as master).
#  The npm package will be validated and published after the code is merged to master.

# Prerequisites: $NPM_TOKEN setup in the Deployment variables.
# For advanced cases, please, follow examples from the pipe's README https://bitbucket.org/atlassian/npm-publish/src/master/README.md

image: node:16

pipelines:
  pull-requests:
    master:
      - step:
          runs-on:
            - self.hosted
            - linux.shell
          name: Build and Test
          caches:
            - node
          script:
            - cd Webapp
            - npm install
            - npm test
            - npm run lint
  branches:
    master:
      - step:
          runs-on:
            - self.hosted
            - linux.shell
          name: Build and Test
          caches:
            - node
          script:
            - cd Webapp
            - npm install
            - npm test
            - npm run lint
