"""Add number of scoring runs to phase information

Revision ID: e1a32f9296a8
Revises: 77c0a8c18e80
Create Date: 2023-11-25 17:36:19.336055

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e1a32f9296a8'
down_revision = '77c0a8c18e80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phase', sa.Column('number_of_runs_for_score', sa.Integer(), nullable=True))
    scoring_runs = sa.table('phase', sa.column('number_of_runs_for_score'))
    op.execute(scoring_runs.update().values(number_of_runs_for_score=2))
    op.alter_column('phase', 'number_of_runs_for_score', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phase', 'number_of_runs_for_score')
    # ### end Alembic commands ###
