"""Add phase to scored move structure

Revision ID: b88a9571adc8
Revises: 8e05b103124b
Create Date: 2023-10-01 12:47:38.291779

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b88a9571adc8"
down_revision = "8e05b103124b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scoredMoves",
        sa.Column("phase_id", postgresql.UUID(as_uuid=True), nullable=False),
    )
    op.create_foreign_key(None, "scoredMoves", "phase", ["phase_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "scoredMoves", type_="foreignkey")
    op.drop_column("scoredMoves", "phase_id")
    # ### end Alembic commands ###
