"""empty message

Revision ID: 23e344e289f3
Revises: 63c5a28675fe
Create Date: 2023-01-02 13:25:12.583460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e344e289f3'
down_revision = '63c5a28675fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
