"""add nonn nullable constraints

Revision ID: 4aecf7cbb980
Revises: d4bc03bc20d2
Create Date: 2023-03-12 11:32:31.700037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4aecf7cbb980"
down_revision = "d4bc03bc20d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "athleteheat", "heat_id", existing_type=postgresql.UUID(), nullable=False
    )
    op.alter_column(
        "athleteheat", "athlete_id", existing_type=postgresql.UUID(), nullable=False
    )
    op.alter_column("heat", "phase_id", existing_type=postgresql.UUID(), nullable=False)
    op.alter_column(
        "phase", "event_id", existing_type=postgresql.UUID(), nullable=False
    )
    op.alter_column("run", "heat_id", existing_type=postgresql.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("run", "heat_id", existing_type=postgresql.UUID(), nullable=True)
    op.alter_column("phase", "event_id", existing_type=postgresql.UUID(), nullable=True)
    op.alter_column("heat", "phase_id", existing_type=postgresql.UUID(), nullable=True)
    op.alter_column(
        "athleteheat", "athlete_id", existing_type=postgresql.UUID(), nullable=True
    )
    op.alter_column(
        "athleteheat", "heat_id", existing_type=postgresql.UUID(), nullable=True
    )
    # ### end Alembic commands ###
