"""add_paddler_heat_relationships_and_paddler-scoresheet

Revision ID: 33e9af80743a
Revises: 7a054990608f
Create Date: 2023-02-26 17:42:43.934751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "33e9af80743a"
down_revision = "7a054990608f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "athleteheat",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("heat_id", postgresql.UUID(), nullable=True),
        sa.Column("athlete_id", postgresql.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athlete.id"],
        ),
        sa.ForeignKeyConstraint(
            ["heat_id"],
            ["heat.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("athleteheat")
    # ### end Alembic commands ###
