"""empty message

Revision ID: 7b1ff74a8fb0
Revises: b356d03c9aa2
Create Date: 2023-04-14 12:47:37.616887

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7b1ff74a8fb0"
down_revision = "b356d03c9aa2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "availableBonuses", "sheet_id", existing_type=postgresql.UUID(), nullable=False
    )
    op.alter_column(
        "availableBonuses", "move_id", existing_type=postgresql.UUID(), nullable=False
    )
    op.alter_column(
        "scoredBonuses", "judge_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "scoredMoves", "judge_id", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scoredMoves", "judge_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "scoredBonuses", "judge_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "availableBonuses", "move_id", existing_type=postgresql.UUID(), nullable=True
    )
    op.alter_column(
        "availableBonuses", "sheet_id", existing_type=postgresql.UUID(), nullable=True
    )
    # ### end Alembic commands ###
