"""Change Bib type to number.

Revision ID: 77c0a8c18e80
Revises: b88a9571adc8
Create Date: 2023-11-25 17:33:37.241487

"""


# revision identifiers, used by Alembic.
revision = "77c0a8c18e80"
down_revision = "b88a9571adc8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
