"""add last phase rank to athlete heat relationship

Revision ID: a16cc7d14a36
Revises: 74fecaa4ec6e
Create Date: 2024-01-01 14:24:04.317046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16cc7d14a36'
down_revision = '74fecaa4ec6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athleteheat', sa.Column('last_phase_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athleteheat', 'last_phase_rank')
    # ### end Alembic commands ###
