"""Add Run Status

Revision ID: 611a62dfbf51
Revises: a16cc7d14a36
Create Date: 2024-11-30 19:18:29.441936

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "611a62dfbf51"
down_revision = "a16cc7d14a36"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runStatus",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("heat_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("run_number", sa.Integer(), nullable=False),
        sa.Column("phase_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("athlete_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("did_not_start", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athlete.id"],
        ),
        sa.ForeignKeyConstraint(
            ["heat_id"],
            ["heat.id"],
        ),
        sa.ForeignKeyConstraint(
            ["phase_id"],
            ["phase.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("runStatus")
    # ### end Alembic commands ###
