"""Fix error from  nullable primary keys

Revision ID: e42976f626a0
Revises: 611a62dfbf51
Create Date: 2025-01-11 12:43:52.561748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e42976f626a0'
down_revision = '611a62dfbf51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('sth_uq_athlete_id'), 'athlete', ['id'])
    op.create_unique_constraint(op.f('sth_uq_athleteheat_id'), 'athleteheat', ['id'])
    op.create_unique_constraint(op.f('sth_uq_availableBonuses_id'), 'availableBonuses', ['id'])
    op.create_unique_constraint(op.f('sth_uq_availableMoves_id'), 'availableMoves', ['id'])
    op.create_unique_constraint(op.f('sth_uq_competition_id'), 'competition', ['id'])
    op.create_unique_constraint(op.f('sth_uq_event_id'), 'event', ['id'])
    op.create_unique_constraint(op.f('sth_uq_heat_id'), 'heat', ['id'])
    op.create_unique_constraint(op.f('sth_uq_phase_id'), 'phase', ['id'])
    op.create_unique_constraint(op.f('sth_uq_runStatus_id'), 'runStatus', ['id'])
    op.alter_column('scoreSheet', 'id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='Competition ID',
               existing_nullable=False)
    op.create_unique_constraint(op.f('sth_uq_scoreSheet_id'), 'scoreSheet', ['id'])
    op.create_unique_constraint(op.f('sth_uq_scoredBonuses_id'), 'scoredBonuses', ['id'])
    op.create_unique_constraint(op.f('sth_uq_scoredMoves_id'), 'scoredMoves', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sth_uq_scoredMoves_id'), 'scoredMoves', type_='unique')
    op.drop_constraint(op.f('sth_uq_scoredBonuses_id'), 'scoredBonuses', type_='unique')
    op.drop_constraint(op.f('sth_uq_scoreSheet_id'), 'scoreSheet', type_='unique')
    op.alter_column('scoreSheet', 'id',
               existing_type=postgresql.UUID(),
               comment='Competition ID',
               existing_nullable=False)
    op.drop_constraint(op.f('sth_uq_runStatus_id'), 'runStatus', type_='unique')
    op.drop_constraint(op.f('sth_uq_phase_id'), 'phase', type_='unique')
    op.drop_constraint(op.f('sth_uq_heat_id'), 'heat', type_='unique')
    op.drop_constraint(op.f('sth_uq_event_id'), 'event', type_='unique')
    op.drop_constraint(op.f('sth_uq_competition_id'), 'competition', type_='unique')
    op.drop_constraint(op.f('sth_uq_availableMoves_id'), 'availableMoves', type_='unique')
    op.drop_constraint(op.f('sth_uq_availableBonuses_id'), 'availableBonuses', type_='unique')
    op.drop_constraint(op.f('sth_uq_athleteheat_id'), 'athleteheat', type_='unique')
    op.drop_constraint(op.f('sth_uq_athlete_id'), 'athlete', type_='unique')
    # ### end Alembic commands ###
