"""add bonus display order

Revision ID: d66d428a8a11
Revises: 4b23a86a22d0
Create Date: 2025-03-30 15:39:20.080339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66d428a8a11'
down_revision = '4b23a86a22d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availableBonuses', sa.Column('display_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('availableBonuses', 'display_order')
    # ### end Alembic commands ###
