"""Add athlete affiliation

Revision ID: 4b23a86a22d0
Revises: 4761b40f88dd
Create Date: 2025-03-02 18:09:43.207636

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4b23a86a22d0"
down_revision = "4761b40f88dd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("athlete", sa.Column("affiliation", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("athlete", "affiliation")
    # ### end Alembic commands ###
