"""add bonus display order

Revision ID: d66d428a8a11
Revises: 4b23a86a22d0
Create Date: 2025-03-30 15:39:20.080339

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d66d428a8a11"
down_revision = "4b23a86a22d0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bonus_order = {"Air": 0, "Huge": 1, "Clean": 2, "SuperClean": 3, "Link": 4}
    op.add_column(
        "availableBonuses", sa.Column(
            "display_order", sa.Integer(), nullable=True)
    )

    # Check if the "name" column exists and populate display_order if possible
    conn = op.get_bind()
    result = conn.execute(
        "SELECT column_name FROM information_schema.columns WHERE table_name='availableBonuses' AND column_name='name'"
    )
    if result.fetchone() is not None:
        for bonus, order in bonus_order.items():
            conn.execute(
                f'UPDATE "availableBonuses" SET display_order = {order} WHERE name = {bonus}'
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("availableBonuses", "display_order")
    # ### end Alembic commands ###
