"""Update Default Values allocation ot use server_default

Revision ID: 4761b40f88dd
Revises: e42976f626a0
Create Date: 2025-01-17 22:28:12.230905

"""

# revision identifiers, used by Alembic.
revision = "4761b40f88dd"
down_revision = "e42976f626a0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
