"""empty message

Revision ID: 871d29530095
Revises: 
Create Date: 2022-09-10 11:29:41.755663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871d29530095'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_o2o',
    sa.Column('id', sa.Integer(), nullable=False, comment='test-test-test'),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('child_o2o',
    sa.Column('id', sa.Integer(), nullable=False, comment='child_pk_test'),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parent_o2o.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('child_o2o')
    op.drop_table('parent_o2o')
    # ### end Alembic commands ###
