FROM mcr.microsoft.com/devcontainers/python:1-3.10-bullseye

ENV PYTHONUNBUFFERED 1
ENV PATH="/workspaces/AEMS/Server/.venv/bin:$PATH"
# [Optional] If your requirements rarely change, uncomment this section to add them to the image.
# COPY requirements.txt /tmp/pip-tmp/
# RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
#    && rm -rf /tmp/pip-tmp
# [Optional] Uncomment this section to install additional OS packages.
# RUN set -e \
# 	&& apt-get update \
# 	&& apt-get install -y --no-install-recommends curl ca-certificates \
# 	&& apt-get clean \
# 	&& rm -rf /var/lib/apt/lists/*
