const nextJest = require("next/jest")

const createJestConfig = nextJest({
	dir: "./"
})

const customJestConfig = {
	testEnvironment: "jsdom",
	setupFiles: ["<rootDir>/jest.polyfills.js"],
	moduleNameMapper: {
		"^msw/node$": "<rootDir>/node_modules/msw/lib/node/index.js",
		"^@mswjs/interceptors/ClientRequest$":
			"<rootDir>/node_modules/@mswjs/interceptors/lib/node/interceptors/ClientRequest/index.cjs",
		"^@mswjs/interceptors/XMLHttpRequest$":
			"<rootDir>/node_modules/@mswjs/interceptors/lib/node/interceptors/XMLHttpRequest/index.cjs",
		"^@mswjs/interceptors/fetch$":
			"<rootDir>/node_modules/@mswjs/interceptors/lib/node/interceptors/fetch/index.cjs",
		"^until-async$": "<rootDir>/__mocks__/until-async.js",
		"^@/components/(.*)$": "<rootDir>/src/components/$1",
		"^@/pages/(.*)$": "<rootDir>/src/pages/$1"
	},
	setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
	collectCoverage: true,
	coverageDirectory: "coverage",
	coverageReporters: ["json", "lcov", "text", "clover"],
	coveragePathIgnorePatterns: [
		"/node_modules/",
		"/src/mocks/", // MSW boilerplate
		"/src/redux/services/aemsApi.ts", // autogenerated API file
		"/src/components/roles/scribe/tests/TestData.ts", // Test data file
		"/src/setupTests.ts", // Test setup
		"/src/testUtils.tsx", // Test utilities
		"/src/reportWebVitals.ts" // Web vitals reporting
	],
	collectCoverageFrom: ["src/**/*.{ts,tsx}", "!src/**/*.d.ts"]
}

module.exports = createJestConfig(customJestConfig)
